/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Franklin
 */
public class Comandas extends javax.swing.JFrame {

    /**
     * Creates new form Comandas
     */
    public Comandas() {
        initComponents();
        
        setSize(660, 519);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton22 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(23, 21, 21));
        jPanel1.setLayout(null);

        jToggleButton13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton13.setText("Comanda 7");
        jPanel1.add(jToggleButton13);
        jToggleButton13.setBounds(210, 280, 111, 74);

        jToggleButton14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton14.setText("Comanda 8");
        jPanel1.add(jToggleButton14);
        jToggleButton14.setBounds(210, 370, 111, 74);

        jToggleButton15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton15.setText("Comanda 11");
        jPanel1.add(jToggleButton15);
        jToggleButton15.setBounds(350, 280, 111, 74);

        jToggleButton20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton20.setText("Comanda 12");
        jToggleButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton20ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton20);
        jToggleButton20.setBounds(350, 370, 111, 74);

        jToggleButton21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton21.setText("Comanda 9");
        jPanel1.add(jToggleButton21);
        jToggleButton21.setBounds(350, 100, 111, 74);

        jToggleButton16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton16.setText("Comanda 14");
        jPanel1.add(jToggleButton16);
        jToggleButton16.setBounds(490, 190, 111, 74);

        jToggleButton22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton22.setText("Comanda 10");
        jPanel1.add(jToggleButton22);
        jToggleButton22.setBounds(350, 190, 111, 74);

        jToggleButton17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton17.setText("Comanda 15");
        jPanel1.add(jToggleButton17);
        jToggleButton17.setBounds(490, 280, 111, 74);

        jToggleButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton7.setText("Comanda 1");
        jPanel1.add(jToggleButton7);
        jToggleButton7.setBounds(60, 100, 111, 74);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Comandas");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(260, 20, 212, 45);

        jToggleButton18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton18.setText("Comanda 16");
        jPanel1.add(jToggleButton18);
        jToggleButton18.setBounds(490, 370, 111, 74);

        jToggleButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton8.setText("Comanda 2");
        jPanel1.add(jToggleButton8);
        jToggleButton8.setBounds(60, 190, 111, 74);

        jToggleButton19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton19.setText("Comanda 13");
        jPanel1.add(jToggleButton19);
        jToggleButton19.setBounds(490, 100, 111, 74);

        jToggleButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton9.setText("Comanda 3");
        jPanel1.add(jToggleButton9);
        jToggleButton9.setBounds(60, 280, 111, 74);

        jToggleButton11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton11.setText("Comanda 5");
        jPanel1.add(jToggleButton11);
        jToggleButton11.setBounds(210, 100, 111, 74);

        jToggleButton10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton10.setText("Comanda 4");
        jPanel1.add(jToggleButton10);
        jToggleButton10.setBounds(60, 370, 111, 74);

        jToggleButton12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton12.setText("Comanda 6");
        jPanel1.add(jToggleButton12);
        jToggleButton12.setBounds(210, 190, 111, 74);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton20ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comandas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comandas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comandas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comandas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comandas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
}
